#thymeleaf
spring:
      thymeleaf:
                prefix: classpath:/templates/
                suffix: .html
                cache: false
                content-type: text/html
                enabled: true
                encoding: UTF-8
                mode: HTML5

# druid
      datasource:
                url: jdbc:mysql://localhost:3306/seckilling?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
                username: root
                password:
                driver-class-name: com.mysql.jdbc.Driver
                type: com.alibaba.druid.pool.DruidDataSource
                filters: stat
                maxActive: 1000
                initialSize: 1000
                maxWait: 60000
                minIdle: 1000
                timeBetweenEvictionRunsMillis: 60000
                minEvictableIdleTimeMillis: 300000
                validationQuery: select 'x'
                testWhileIdle: true
                testOnBorrow: false
                testOnReturn: false
                poolPreparedStatements: true
                maxOpenPreparedStatements: 200

#static
      resources:
               add-mappings: true
               cache-period: 3600
               chain.cache: true
               chain.enabled: true
               chain.gzipped: true
               chain.html-application-cache: true
               static-locations: classpath:/static/

# mybatis
mybatis:
       typeAliasesPackage: com.astro.domain
       configuration:
                   map-underscore-to-camel-case:  true
                   default-fetch-size: 100
                   default-statement-timeout: 3000
      # mapperLocations : classpath:com/imooc/miaosha/dao/*.xml

#redis
redis:
      #host: 119.29.107.227
      host: localhost
      port: 6379
      timeout: 100
      poolMaxTotal: 1000
      poolMaxIdle: 500
      poolMaxWait: 500
server:
  port: 8080


